services:
 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      
  backend:
    build: ./backend
    ports:
      - "5051:5051"
    environment:
      - DATABASE_URL=postgresql://postgres:admin@89123@db:5432/cheque_parser
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=cheque_parser
      - POSTGRES_PASSWORD=admin@89123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - react_build:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend


  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email your-email@example.com -d 172.105.50.148 --agree-tos

volumes:
  postgres_data:
  react_build: