FROM python:3.9-slim-buster

# Install system dependencies
RUN apt-get update && apt-get install -y \
    poppler-utils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Set Google Cloud credentials
ENV GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json

CMD ["gunicorn", "--bind", "0.0.0.0:5050", "app:app"]